# Generated by Django 3.1.4 on 2020-12-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_cor',
            field=models.CharField(max_length=45, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_tamanho',
            field=models.CharField(max_length=45, null=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='dt_entrada',
            field=models.DateField(null=True, verbose_name='Data de entrada'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='id_produto',
            field=models.IntegerField(null=True, verbose_name='Id produto'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='tx_lucro',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de lucro'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='vl_preco_custo',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='vl_preco_venda',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Preco de venda'),
        ),
    ]
