# Generated by Django 3.1.4 on 2020-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201207_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_tamanho',
            field=models.BooleanField(null=True, verbose_name='Tamanho'),
        ),
    ]
