# Generated by Django 3.1.4 on 2020-12-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201208_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=45)),
            ],
        ),
    ]
