# Generated by Django 3.1.4 on 2020-12-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tb_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_cor',
            field=models.IntegerField(null=True, verbose_name='Cor'),
        ),
    ]
