# Generated by Django 3.1.4 on 2020-12-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201208_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_cor',
            field=models.CharField(max_length=10, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_tamanho',
            field=models.CharField(max_length=2, null=True, verbose_name='Tamanho'),
        ),
    ]
