# Generated by Django 3.1.4 on 2020-12-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_tb_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_cliente',
            name='cep',
            field=models.IntegerField(verbose_name='CEP'),
        ),
    ]
