# Generated by Django 3.1.4 on 2020-12-08 13:39

import cpf_field.models
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201208_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
            ],
        ),
    ]
