# Generated by Django 3.1.4 on 2020-12-08 13:49

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_tb_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cnpj', models.IntegerField(verbose_name='CNPJ')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('codigo', models.IntegerField(verbose_name='Codigo do produto')),
                ('tipo', models.CharField(max_length=45, verbose_name='Tipo: Blusa / Saia / Calça')),
            ],
        ),
    ]
