# Generated by Django 3.1.4 on 2020-12-08 14:13

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_tb_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_vendas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor do pedido')),
                ('cep', models.IntegerField(verbose_name='CEP')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço do cliente')),
                ('dt', models.DateField(verbose_name='Data do pedido')),
                ('codigo', models.IntegerField(verbose_name='Codigo do produto')),
                ('status', models.CharField(max_length=45, verbose_name='Status: Separando / Processando / Entregue / Cancelado')),
            ],
        ),
    ]
