# Generated by Django 3.1.4 on 2020-12-08 14:29

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_tb_vendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_vendas',
            name='cep',
            field=models.IntegerField(verbose_name='CEP do cliente'),
        ),
        migrations.AlterField(
            model_name='tb_vendas',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf do cliente'),
        ),
    ]
