# Generated by Django 3.2.3 on 2021-05-26 14:35

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20201208_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tb_vendas',
        ),
        migrations.AlterModelOptions(
            name='tb_cliente',
            options={'ordering': ('nome',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='tb_estoque',
            options={'ordering': ('ds_n',), 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoque'},
        ),
        migrations.AlterModelOptions(
            name='tb_fornecedor',
            options={'ordering': ('nome',), 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='tb_usuario',
            options={'ordering': ('nome',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='tb_cliente',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='tb_fornecedor',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True, verbose_name='Cep'),
        ),
        migrations.AlterField(
            model_name='tb_fornecedor',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='tb_usuario',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, null=True, verbose_name='Cep'),
        ),
    ]
