# Generated by Django 3.2.3 on 2021-06-17 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210526_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_cor',
            field=models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Verde', 'Verde'), ('Rosa', 'Rosa'), ('Vermelho', 'Vermelho')], max_length=10, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='tb_estoque',
            name='ds_tamanho',
            field=models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2, null=True, verbose_name='Tamanho'),
        ),
        migrations.AlterField(
            model_name='tb_fornecedor',
            name='tipo',
            field=models.CharField(choices=[('Blusa', 'Blusa'), ('Saia', 'Saia'), ('Calça', 'Calça'), ('Moletom', 'Moletom'), ('Bone', 'Bone')], max_length=45, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2, null=True, verbose_name='Tamanho')),
                ('cor', models.CharField(choices=[('Branco', 'Branco'), ('Preto', 'Preto'), ('Verde', 'Verde'), ('Rosa', 'Rosa'), ('Vermelho', 'Vermelho')], max_length=10, null=True, verbose_name='Cor')),
                ('newV', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Preco da venda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.tb_cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.tb_estoque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.tb_usuario')),
            ],
            options={
                'verbose_name': 'Carrinho',
                'verbose_name_plural': 'Carrinho',
            },
        ),
    ]
