# Generated by Django 3.2.3 on 2021-06-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20210617_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_cliente',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
